//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesMetadata
    {
        public string Path { get; set; }
        public Nullable<long> Size { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastAccessed { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public string Md5Hash { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public int Depth { get; set; }
        public string Attributes { get; set; }
        public int PathLength { get; set; }
    }
}
